### PR TITLE
change folder from 'src' to 'Sources'

### PR DESCRIPTION
**Pull request by lewislepton**
the naming for the folder makes it easier for others to use khambe within haxelib, rather than having to import it all the time.
it does work as well this way, just tried ;)

but kha libraries use 'Sources'

### CODE REVIEW

**Comment by sourcreme** [comment]
Lewis I was unaware that Kha had a specific convention for libraries. In the khambe-example https://github.com/sourcreme/khambe-example I listed khambe as a submodule so that it can be easily updated with "git submodule foreach --recursive git pull origin master". I find that to be an easier solution as it keeps everything up to date.

**Comment by sourcreme** [comment]
Then modify khafile.js to include "project.addParameter('-cp ../khambe/src');" If I'm incorrect I'm more than happy to change it.

**Comment by lewislepton** [comment]
yeah its a bit weird, i was the same when rolling out a little library i wanted on my git repo, but it does make it easier.

but rather than downloading many different khambe for different projects, you could do something like
`cd /usr/local/lib/haxe/lib/khambe/git` which aims to my stored khambe folder, then do `sudo git submodule foreach --recursive git pull origin master`
that would do the same thing, but not have you create many different instances of khambe for different projects

**Comment by lewislepton** [comment]
thats how i do the updating of kha for myself as well

**Comment by lewislepton** [comment]
also as well you can then just do 
`project.addLibrary('khambe')`
instead

**Pull request merged**
